version: '3'
services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - REDIS_URL=redis://db:6379/0
    depends_on:
      - db
    volumes:
      - artifacts:/app/coverage
  db:
    image: redis
    ports:
      - "6379"
volumes:
  artifacts:
